name: Deploy

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      TF_FORCE_LOCAL_BACKEND: 1
      TF_TOKEN_app_terraform_io: ${{ secrets.HCP_TERRAFORM_TOKEN }}
      DIGITALOCEAN_TOKEN: ${{ secrets.DIGITALOCEAN_API_TOKEN }}
      TF_VAR_ssh_key_name: ${{ vars.DO_KEY_NAME }}
    defaults:
      run:
        working-directory: terraform
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate -no-color

      - name: Terraform Apply
        run: terraform apply -no-color --auto-approve

      - name: Configure server
        uses: dawidd6/action-ansible-playbook@v2.8.0
        with:
          playbook: setup.yaml
          directory: ansible
          key: ${{ secrets.SSH_PRIV_KEY }}
          options: |
            --inventory inventory_digitalocean.yaml

      - name: Login to DigitalOcean Container Registry
        uses: docker/login-action@v3
        with:
          registry: registry.digitalocean.com
          username: ${{ vars.DIGITALOCEAN_USERNAME }}
          password: ${{ secrets.DIGITALOCEAN_API_TOKEN }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v6.13.0
        with:
          context: "hello-world-app"
          push: true
